sonar.projectKey=aresta-workflow-manager
sonar.projectName=ARESTA WORKFLOW MANAGER
sonar.sourceEncoding=UTF-8

sonar.sources=app,config,database,resources,routes
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/build/**,bootstrap/cache/**,storage/**

sonar.php.coverage.reportPaths=coverage.xml
